spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_db
    username: admin
    password: pa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


Cloudinary:
  cloud_name: seu_cloud_name
  api_key: sua_api_key
  api_secret: seu_api_secret


jwt:
  secret: (|:Psli#CdvTKjJ2u&)GK.7Yd42mgvl0,#Bz|F6NZ)q*>!1zj/gzu9{tdr&stltIiz46z;b8Htq_tLy;ZMB#|s
  expiration: 43200000