server:
  port: ${PORT:8082}
  tomcat:
    max-http-form-post-size: 14MB
    max-swallow-size: -1
    max-part-count: 50

  servlet:
    multipart:
      enabled: true
      max-file-size: 14MB
      max-request-size: 14MB

app:
  frontend-url: ${FRONT_END_URL}
  brevo:
    api-key: ${BREVO_API_KEY}
    base-url: https://api.brevo.com/v3

  mail:
    from: ${MAIL_FROM}
    from-name: ${MAIL_FROM_NAME:Libertad Comercial e Serviços}
    commercial-to: ${MAIL_COMMERCIAL_TO}
    ouvidoria-to: ${OUVIDORIA_MAIL}
