server:
  port: ${PORT:8082}
  tomcat:
    max-http-form-post-size: 50MB
    max-swallow-size: -1

spring:
  mail:
    host: ${MAIL_SMTP}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

app:
  frontend-url: ${FRONT_END_URL}
  mail:
    commercial-to: ${COMMERCIAL_TEAM_EMAIL}
    ouvidoria-to: ${OUVIDORIA_MAIL}
  cnpj:
    api-url: ${CNPJ_API_URL}